/**
 * A list of names "labels" for pipeline "signals"
 */
export const Labels = Object.freeze([
    "ifPC",
    "ifInst",
    "deInst",
    "deDataA",
    "deDataB",
    "deRS1",
    "deRS2",
    // "deRegDataA",
    // "deRegDataB",
    "deImmed",
    "dePC",
    "deBypassA",
    "deBypassB",
    "exInst",
    "exDataA",
    "exDataB",
    "exAluData",
    "exStoreData",
    "exBranchAddr",
    // "exBranchBase",
    // "exImmed",
    "exBranchTaken",
    "exPC",
    "maInst",
    "maStoreData",
    "maLoadData",
    // "maAddr",
    "maAluData",
    "maLoadOp",
    "maWriteBackData",
    "maPC",
    "wbInst",
    "wbRD",
    "wbStoreData",
    // "wbPC",
    // "branch",
    // "dataHazard",
]);